### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by yoonjason** [fimuxd/BringMyOwnBeer-#5]
올려주신 예제를 보고 네이버 테크 콘서트에서 영상을 보려했으나, 영상이 삭제되었더라구요.ㅠ

전부 설명을 영상에서 하진 않으셨겠지만, 혹시 영상을 가지고 계시면 볼 수 있는 링크나 영상을 부탁드려도 될까요?

프로젝트 예제가 이해가 잘 되지않아, 영상이라도 보고 싶습니다 ㅠ

rx+MVVM을 익숙하게 사용하고 싶은 데, 잘 안되서요.

염치불구하고 요청 좀 드려도 될까요?

좋은 주말 되세요! :)

**Comment by fimuxd** [comment]
안녕하세요. 이제서야 코멘트 남기신 것을 확인했네요. 
[Naver TechConcert 2019 영상](https://tv.naver.com/v/9342795) 입니다.  
너무 늦었지만.. ㅎㅎ
